# Generated by Django 3.2.13 on 2022-06-04 02:22

from django.db import migrations, models
import paquetes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('pasaporte', models.IntegerField()),
                ('vencimiento', models.DateField()),
                ('dni', models.IntegerField()),
                ('domicilio', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paquete', models.CharField(max_length=30)),
                ('cantidad_pasajeros', models.IntegerField()),
                ('dias', models.IntegerField()),
                ('fecha_partida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('fecha_venta', models.DateField(auto_now=True)),
                ('forma_pago', models.CharField(choices=[('Tr', 'Transferencia bancaria'), ('TC', 'Tarjeta de credito'), ('TD', 'Tarjeta de debito'), ('MP', 'Mercado Pago')], max_length=2)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('dias', models.DateField()),
                ('fecha_partida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('precio_publico', models.FloatField()),
                ('costo', models.FloatField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('SU', 'Super_user'), ('RU', 'Regular_user')], max_length=2)),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('last_login', models.DateField()),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
